# Generated by Django 4.0.4 on 2022-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_header', models.CharField(max_length=200)),
                ('game_name', models.CharField(max_length=150)),
                ('post_text', models.CharField(max_length=5000)),
                ('game_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
