# Generated by Django 4.0.4 on 2022-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_user_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
