# Generated by Django 4.0.4 on 2022-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_user_posts_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='game_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
