# Generated by Django 4.0.4 on 2022-06-26 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_user_posts_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='game_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
